"""add driver vehicle documents and inspections

Revision ID: 422e7ceedade
Revises: 38af683fde60
Create Date: 2026-09-13 23:26:57.963008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '422e7ceedade'
down_revision: Union[str, Sequence[str], None] = '38af683fde60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=150), nullable=True),
    sa.Column('issuing_authority', sa.String(length=150), nullable=True),
    sa.Column('issuing_country', sa.String(length=2), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verification_status IN ('pending', 'approved', 'rejected', 'suspended')", name='ck_driver_documents_verification_status'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_documents_document_type'), 'driver_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_driver_documents_driver_id'), 'driver_documents', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_documents_expires_at'), 'driver_documents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_driver_documents_verification_status'), 'driver_documents', ['verification_status'], unique=False)
    op.create_index(op.f('ix_driver_documents_verified_by'), 'driver_documents', ['verified_by'], unique=False)
    op.create_table('vehicle_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=150), nullable=True),
    sa.Column('issuing_authority', sa.String(length=150), nullable=True),
    sa.Column('issuing_country', sa.String(length=2), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verification_status IN ('pending', 'approved', 'rejected', 'suspended')", name='ck_vehicle_documents_verification_status'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_documents_document_type'), 'vehicle_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_expires_at'), 'vehicle_documents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_vehicle_id'), 'vehicle_documents', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_verification_status'), 'vehicle_documents', ['verification_status'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_verified_by'), 'vehicle_documents', ['verified_by'], unique=False)
    op.create_table('vehicle_inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=True),
    sa.Column('inspection_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_location', sa.String(length=250), nullable=True),
    sa.Column('inspection_provider', sa.String(length=150), nullable=True),
    sa.Column('inspection_reference', sa.String(length=100), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('checklist_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'in_progress', 'passed', 'failed', 'reinspection_required', 'cancelled')", name='ck_vehicle_inspections_status'),
    sa.CheckConstraint('odometer_km IS NULL OR odometer_km >= 0', name='ck_vehicle_inspections_odometer_nonnegative'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_inspections_expires_at'), 'vehicle_inspections', ['expires_at'], unique=False)
    op.create_index(op.f('ix_vehicle_inspections_inspected_at'), 'vehicle_inspections', ['inspected_at'], unique=False)
    op.create_index(op.f('ix_vehicle_inspections_inspection_reference'), 'vehicle_inspections', ['inspection_reference'], unique=False)
    op.create_index(op.f('ix_vehicle_inspections_inspection_type'), 'vehicle_inspections', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_vehicle_inspections_inspector_id'), 'vehicle_inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_vehicle_inspections_status'), 'vehicle_inspections', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_inspections_vehicle_id'), 'vehicle_inspections', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_inspections_vehicle_id'), table_name='vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_inspections_status'), table_name='vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_inspections_inspector_id'), table_name='vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_inspections_inspection_type'), table_name='vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_inspections_inspection_reference'), table_name='vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_inspections_inspected_at'), table_name='vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_inspections_expires_at'), table_name='vehicle_inspections')
    op.drop_table('vehicle_inspections')
    op.drop_index(op.f('ix_vehicle_documents_verified_by'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_verification_status'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_vehicle_id'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_expires_at'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_document_type'), table_name='vehicle_documents')
    op.drop_table('vehicle_documents')
    op.drop_index(op.f('ix_driver_documents_verified_by'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_verification_status'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_expires_at'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_driver_id'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_document_type'), table_name='driver_documents')
    op.drop_table('driver_documents')
    # ### end Alembic commands ###
