"""add core ride engine tables

Revision ID: c41d2e7f9a30
Revises: 9b7c4e2d1a6f
Create Date: 2026-09-16 22:36:15.081744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c41d2e7f9a30'
down_revision: Union[str, Sequence[str], None] = '9b7c4e2d1a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'operation', 'idempotency_key', name='uq_idempotency_user_operation_key')
    )
    op.create_index(op.f('ix_idempotency_records_expires_at'), 'idempotency_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_user_id'), 'idempotency_records', ['user_id'], unique=False)
    op.create_table('ride_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('ride_mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('pickup_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('destination_address', sa.String(length=500), nullable=False),
    sa.Column('destination_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('destination_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('recommended_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_offer_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quick_ride_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_counteroffer_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rider_offer_fare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('matched_fare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("payment_method IN ('cash', 'electronic')", name='ck_ride_requests_payment_method'),
    sa.CheckConstraint("ride_mode IN ('quick_ride', 'negotiate')", name='ck_ride_requests_ride_mode'),
    sa.CheckConstraint("status IN ('requested', 'searching', 'matched', 'rider_cancelled', 'no_driver_found', 'expired')", name='ck_ride_requests_status'),
    sa.CheckConstraint('maximum_counteroffer_fare > 0', name='ck_ride_requests_max_counter_positive'),
    sa.CheckConstraint('minimum_offer_fare > 0', name='ck_ride_requests_minimum_offer_positive'),
    sa.CheckConstraint('quick_ride_fare > 0', name='ck_ride_requests_quick_fare_positive'),
    sa.CheckConstraint('recommended_fare > 0', name='ck_ride_requests_recommended_fare_positive'),
    sa.ForeignKeyConstraint(['rider_id'], ['rider_profiles.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_requests_rider_id'), 'ride_requests', ['rider_id'], unique=False)
    op.create_index(op.f('ix_ride_requests_status'), 'ride_requests', ['status'], unique=False)
    op.create_table('ride_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_request_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('rider_offer_fare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('driver_counteroffer_fare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'accepted', 'countered', 'declined', 'expired', 'selected', 'closed')", name='ck_ride_offers_status'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_request_id', 'driver_id', name='uq_ride_offers_request_driver')
    )
    op.create_index(op.f('ix_ride_offers_driver_id'), 'ride_offers', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ride_offers_expires_at'), 'ride_offers', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ride_offers_ride_request_id'), 'ride_offers', ['ride_request_id'], unique=False)
    op.create_index(op.f('ix_ride_offers_status'), 'ride_offers', ['status'], unique=False)
    op.create_index(op.f('ix_ride_offers_vehicle_id'), 'ride_offers', ['vehicle_id'], unique=False)
    op.create_table('driver_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_request_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('ride_offer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=1000), nullable=True),
    sa.Column('pickup_eta_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'cancelled', 'replaced', 'completed')", name='ck_driver_assignments_status'),
    sa.CheckConstraint('pickup_eta_seconds IS NULL OR pickup_eta_seconds >= 0', name='ck_driver_assignments_pickup_eta_nonnegative'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ride_offer_id'], ['ride_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_assignments_driver_id'), 'driver_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_ride_offer_id'), 'driver_assignments', ['ride_offer_id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_ride_request_id'), 'driver_assignments', ['ride_request_id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_status'), 'driver_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_driver_assignments_vehicle_id'), 'driver_assignments', ['vehicle_id'], unique=False)
    op.create_index('uq_driver_assignments_active_driver', 'driver_assignments', ['driver_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_driver_assignments_active_request', 'driver_assignments', ['ride_request_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_request_id', sa.UUID(), nullable=False),
    sa.Column('active_assignment_id', sa.UUID(), nullable=True),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('agreed_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('driver_arriving_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'electronic')", name='ck_trips_payment_method'),
    sa.CheckConstraint("status IN ('matched', 'driver_arriving', 'driver_arrived', 'in_progress', 'completed', 'rider_cancelled', 'rider_no_show', 'terminated')", name='ck_trips_status'),
    sa.CheckConstraint('agreed_fare > 0', name='ck_trips_agreed_fare_positive'),
    sa.ForeignKeyConstraint(['active_assignment_id'], ['driver_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['rider_profiles.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_active_assignment_id'), 'trips', ['active_assignment_id'], unique=False)
    op.create_index(op.f('ix_trips_ride_request_id'), 'trips', ['ride_request_id'], unique=True)
    op.create_index(op.f('ix_trips_rider_id'), 'trips', ['rider_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_table('trip_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_request_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_events_actor_user_id'), 'trip_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_trip_events_created_at'), 'trip_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_trip_events_event_type'), 'trip_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_trip_events_ride_request_id'), 'trip_events', ['ride_request_id'], unique=False)
    op.create_index(op.f('ix_trip_events_trip_id'), 'trip_events', ['trip_id'], unique=False)
    op.create_table('trip_start_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name='ck_trip_start_verifications_attempt_count'),
    sa.ForeignKeyConstraint(['assignment_id'], ['driver_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'assignment_id', name='uq_trip_start_verifications_trip_assignment')
    )
    op.create_index(op.f('ix_trip_start_verifications_assignment_id'), 'trip_start_verifications', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_trip_start_verifications_trip_id'), 'trip_start_verifications', ['trip_id'], unique=False)
    op.create_table('trip_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_request_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stop_type', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('planned_before_matching', sa.Boolean(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_wait_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stop_type IN ('pickup', 'intermediate', 'destination')", name='ck_trip_stops_stop_type'),
    sa.CheckConstraint('sequence >= 0', name='ck_trip_stops_sequence_nonnegative'),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_request_id', 'sequence', name='uq_trip_stops_request_sequence')
    )
    op.create_index(op.f('ix_trip_stops_ride_request_id'), 'trip_stops', ['ride_request_id'], unique=False)
    op.create_index(op.f('ix_trip_stops_trip_id'), 'trip_stops', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_stops_trip_id'), table_name='trip_stops')
    op.drop_index(op.f('ix_trip_stops_ride_request_id'), table_name='trip_stops')
    op.drop_table('trip_stops')
    op.drop_index(op.f('ix_trip_start_verifications_trip_id'), table_name='trip_start_verifications')
    op.drop_index(op.f('ix_trip_start_verifications_assignment_id'), table_name='trip_start_verifications')
    op.drop_table('trip_start_verifications')
    op.drop_index(op.f('ix_trip_events_trip_id'), table_name='trip_events')
    op.drop_index(op.f('ix_trip_events_ride_request_id'), table_name='trip_events')
    op.drop_index(op.f('ix_trip_events_event_type'), table_name='trip_events')
    op.drop_index(op.f('ix_trip_events_created_at'), table_name='trip_events')
    op.drop_index(op.f('ix_trip_events_actor_user_id'), table_name='trip_events')
    op.drop_table('trip_events')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_rider_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_ride_request_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_active_assignment_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index('uq_driver_assignments_active_request', table_name='driver_assignments', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('uq_driver_assignments_active_driver', table_name='driver_assignments', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_driver_assignments_vehicle_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_status'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_ride_request_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_ride_offer_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_driver_id'), table_name='driver_assignments')
    op.drop_table('driver_assignments')
    op.drop_index(op.f('ix_ride_offers_vehicle_id'), table_name='ride_offers')
    op.drop_index(op.f('ix_ride_offers_status'), table_name='ride_offers')
    op.drop_index(op.f('ix_ride_offers_ride_request_id'), table_name='ride_offers')
    op.drop_index(op.f('ix_ride_offers_expires_at'), table_name='ride_offers')
    op.drop_index(op.f('ix_ride_offers_driver_id'), table_name='ride_offers')
    op.drop_table('ride_offers')
    op.drop_index(op.f('ix_ride_requests_status'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_rider_id'), table_name='ride_requests')
    op.drop_table('ride_requests')
    op.drop_index(op.f('ix_idempotency_records_user_id'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_expires_at'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
