"""add trip stop execution waiting

Revision ID: d7a91c4f2e60
Revises: 888e1769cccb
Create Date: 2026-09-25 21:35:50.190153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7a91c4f2e60'
down_revision: Union[str, Sequence[str], None] = '888e1769cccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'delivered', 'cancelled', 'failed')", name='ck_notification_outbox_status'),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_outbox_dedupe_key')
    )
    op.create_index(op.f('ix_notification_outbox_notification_type'), 'notification_outbox', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_outbox_scheduled_for'), 'notification_outbox', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'), 'notification_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_notification_outbox_stop_id'), 'notification_outbox', ['stop_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_trip_id'), 'notification_outbox', ['trip_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_user_id'), 'notification_outbox', ['user_id'], unique=False)
    op.create_table('trip_stop_location_verification_states',
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('last_sample_id', sa.UUID(), nullable=True),
    sa.Column('last_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('last_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('last_horizontal_accuracy_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('last_distance_to_stop_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_sample_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sample_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_candidate_count', sa.Integer(), nullable=False),
    sa.Column('last_arrival_candidate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('arrival_candidate_count >= 0', name='ck_trip_stop_location_arrival_candidate_count'),
    sa.CheckConstraint('last_distance_to_stop_m IS NULL OR last_distance_to_stop_m >= 0', name='ck_trip_stop_location_distance_nonnegative'),
    sa.CheckConstraint('last_horizontal_accuracy_m IS NULL OR last_horizontal_accuracy_m > 0', name='ck_trip_stop_location_accuracy_positive'),
    sa.ForeignKeyConstraint(['assignment_id'], ['driver_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_index(op.f('ix_trip_stop_location_verification_states_assignment_id'), 'trip_stop_location_verification_states', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_trip_stop_location_verification_states_trip_id'), 'trip_stop_location_verification_states', ['trip_id'], unique=False)
    op.create_table('trip_stop_wait_states',
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('free_wait_seconds', sa.Integer(), nullable=False),
    sa.Column('wait_rate_per_minute', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('driver_exit_right_seconds', sa.Integer(), nullable=False),
    sa.Column('extension_seconds', sa.Integer(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('free_wait_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('driver_exit_right_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_paid_window_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accrued_billable_seconds', sa.Integer(), nullable=False),
    sa.Column('extension_count', sa.Integer(), nullable=False),
    sa.Column('final_billable_seconds', sa.Integer(), nullable=True),
    sa.Column('final_wait_charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(current_paid_window_started_at IS NULL AND authorized_until IS NULL) OR (current_paid_window_started_at IS NOT NULL AND authorized_until IS NOT NULL AND authorized_until >= current_paid_window_started_at)', name='ck_trip_stop_wait_authorized_window'),
    sa.CheckConstraint('accrued_billable_seconds >= 0', name='ck_trip_stop_wait_accrued_nonnegative'),
    sa.CheckConstraint('closed_at IS NULL OR (current_paid_window_started_at IS NULL AND authorized_until IS NULL)', name='ck_trip_stop_wait_closed_window'),
    sa.CheckConstraint('driver_exit_right_seconds >= 0', name='ck_trip_stop_wait_exit_right_nonnegative'),
    sa.CheckConstraint('extension_count >= 0', name='ck_trip_stop_wait_extension_count_nonnegative'),
    sa.CheckConstraint('extension_seconds > 0', name='ck_trip_stop_wait_extension_positive'),
    sa.CheckConstraint('final_billable_seconds IS NULL OR final_billable_seconds >= 0', name='ck_trip_stop_wait_final_seconds_nonnegative'),
    sa.CheckConstraint('final_wait_charge IS NULL OR final_wait_charge >= 0', name='ck_trip_stop_wait_final_charge_nonnegative'),
    sa.CheckConstraint('free_wait_seconds >= 0', name='ck_trip_stop_wait_free_wait_nonnegative'),
    sa.CheckConstraint('wait_rate_per_minute >= 0', name='ck_trip_stop_wait_rate_nonnegative'),
    sa.ForeignKeyConstraint(['assignment_id'], ['driver_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_index(op.f('ix_trip_stop_wait_states_assignment_id'), 'trip_stop_wait_states', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_trip_stop_wait_states_trip_id'), 'trip_stop_wait_states', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_stop_wait_states_trip_id'), table_name='trip_stop_wait_states')
    op.drop_index(op.f('ix_trip_stop_wait_states_assignment_id'), table_name='trip_stop_wait_states')
    op.drop_table('trip_stop_wait_states')
    op.drop_index(op.f('ix_trip_stop_location_verification_states_trip_id'), table_name='trip_stop_location_verification_states')
    op.drop_index(op.f('ix_trip_stop_location_verification_states_assignment_id'), table_name='trip_stop_location_verification_states')
    op.drop_table('trip_stop_location_verification_states')
    op.drop_index(op.f('ix_notification_outbox_user_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_trip_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_stop_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_status'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_scheduled_for'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_notification_type'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    # ### end Alembic commands ###
